class TestRuleRegistry:
    def test_registry_stores_given_rules(self): ...

    def test_registry_ignores_non_rule_classes(self): ...

    def test_registry_throws_exceptions_if_given_rules_contain_duplicates(self): ...

    def test_registry_throws_exception_if_a_given_rule_is_invalid(self): ...
